### ISSUE TITLE
Not validating properly?

### ISSUE THREAD

**Issue by letiesperon** [picandocodigo/ci_uy#2]
Hi! Cool gem.
I'm not seeing how it works though.

> [14] pry(main)> CiUY.validate("1111")
> => true
> [15] pry(main)> CiUY.validate("1.111aa")
> => true
> [16] pry(main)> CiUY.validate("1.111")
> => true

The CIs are not correct but the validation returns true. It would be cool if you controlled at least the length or the presence of letters.

**Comment by picandocodigo** [comment]
Hi @letiesperon, thanks for reporting this. Yeah, it'd make sense to validate the length as well. I'll work on an update soon and you'll be notified on this issue once it's been fixed.

¡Saludos!

**Comment by picandocodigo** [comment]
@letiesperon Actualicé a la [versión 0.1.3](https://rubygems.org/gems/ci_uy/versions/0.1.3), que valida que el número "transformado" sea de al menos 6 dígitos. Por diseño no se validan otros caracteres, para evitar esos mensajes tipo "ingrese su cédula separada por puntos o guiones", y que el usuario use el formato que quiera.

Cualquier otra sugerencia es bienvenida, sino cierro este ticket por ahora.

¡Saludos!
